services:
  dev-db:
    image: postgres:13
    container_name: warpspeed
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: warpspeed-test
    networks:
      - yaunitechnologies

networks:
  yaunitechnologies:
    driver: bridge

volumes:
  redis_data:
    driver: local